apiVersion: v1
kind: Service
metadata:
  name: nyquist-alerts-ingestion-api-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nyquist-alerts-ingestion-api
